### ISSUE TITLE
POIKit-2.0.1启动问题求助

### ISSUE THREAD

**Issue by Waidalie** [Civitasv/AMapPoi#10]
您好开发者，在使用最新版的POIKit时，点击star会显示：

E:\POIKit-2.0.1>cd app

E:\POIKit-2.0.1\app>java -jar spider.jar
错误: 找不到或无法加载主类 com.civitasv.spider.MainApplication
原因: java.lang.NoClassDefFoundError: javafx/application/Application

请问该如何解决，十分感谢您开发的软件！

**Comment by Civitasv** [comment]
安装jdk 1.8
