### ISSUE TITLE
POIKIT2.0版本_基础功能使用疑问

### ISSUE THREAD

**Issue by Frantoki** [Civitasv/AMapPoi#15]
十分感谢各位老师百忙之中阅读我的邮件，以下是我的问题：

使用POIkit过程中，输入【行政区】代码可以成功输出，但输入【自定义】区域geojson文件却没办法输出，显示“开始POI爬取，请勿操作-解析用户geojson文件中-成功解析用户文件”，就此卡住。

我仔细检查我简单的geojson文件没问题，希望老师有空的时候能帮帮我，这对我真的很重要，十分感谢。

附文件代码：

{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              119.30860519409178,
              41.60697150486485
            ],
            [
              119.28757667541502,
              41.59509765066552
            ],
            [
              119.31075096130373,
              41.5806535322673
            ],
            [
              119.3407917022705,
              41.59124620173383
            ],
            [
              119.30860519409178,
              41.60697150486485
            ]
          ]
        ]
      }
    }
  ]
}

**Comment by Civitasv** [comment]
See release [v2.0.2](https://github.com/Civitasv/AMapPoi/releases/tag/v2.0.2)
