### ISSUE TITLE
geojson格式转shp格式，属性名超过10个字符geotools自动截取10个字符导致属性值丢失

### ISSUE THREAD

**Issue by wanglin2** [Civitasv/AMapPoi#16]
![image_1](https://user-images.githubusercontent.com/17272433/197669803-03cbb9fd-a54b-447e-aa4c-f1f03f0de7c9.png)
![image_2](https://user-images.githubusercontent.com/17272433/197669815-e33956d7-c799-49a1-b7c1-ecafbbc9594d.png)

**Comment by wanglin2** [comment]
![image_3](https://user-images.githubusercontent.com/17272433/197671063-ed4f687e-eaad-41c3-9f61-68ba29a4f658.png)

**Comment by wanglin2** [comment]
[地图边界数据.txt](https://github.com/Civitasv/AMapPoi/files/9856809/default.txt)

**Comment by SkyTreeDelivery** [comment]
![image](https://user-images.githubusercontent.com/42891682/197673506-4e80ad4c-45eb-43bf-bc1e-b6620b377f54.png)
你好~这是shp数据格式的限制，后续版本会考虑加入超过限制长度的字段替换的功能。现在还是建议通过文本替换的方式，把字段名改为小于10个字符。

**Comment by wanglin2** [comment]
好的，多谢
