### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by crystal-sy-001** [Civitasv/AMapPoi#20]
Windows系统中点击start.bat后的界面（我已经完成环境配置）
S:\POIKIT\POIKit-2.0.2>cd app

S:\POIKIT\POIKit-2.0.2\app>java -jar spider.jar
错误：无法找到或装入主类 com.civitasv.spider.MainApplication

S:\POIKIT\POIKit-2.0.2\app>pause
请按任意键继续. . .

**Comment by WindchasingHorse** [comment]
https://www.runoob.com/java/java-environment-setup.html看看这个环境软件安装教程

**Comment by crystal-sy-001** [comment]
crystal已经收到你的邮件，新年快乐~
