### ISSUE TITLE
赞赞赞

### ISSUE THREAD

**Issue by zdctake** [Civitasv/AMapPoi#3]
太强了，直接解决了python迭代问题，我还在想要不要分块一点点做，膜拜大佬
![src=http___image biaobaiju com_uploads_20191102_15_1572678922-dJLfpblhRG jpeg refer=http___image biaobaiju](https://user-images.githubusercontent.com/79126949/120895882-920e6680-c651-11eb-9d4c-2f77546abb8a.jpg)

**Comment by Civitasv** [comment]
有帮助就好
