### ISSUE TITLE
有网站售卖你们的工具

### ISSUE THREAD

**Issue by ariwori** [Civitasv/AMapPoi#5]
### 问题
这里详细描述您的问题

### 参数设置
这里描述您产生该问题使用的参数

### 环境
* jdk 版本
* POIKit 版本

### 重现步骤
告诉开发者如何重现该错误

### 截图
一张或多张该问题相关截图

有网站售卖你们的工具
https://giscloud.com.cn/547.html

**Comment by Civitasv** [comment]
感谢反馈，看了下，已经卖了37份了😔
