### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sobrietyyyyy** [Civitasv/AMapPoi#6]
你好，最近在使用poikit的0.0.7版本时，发现在爬取一二线城市（例如北京、上海、广州、武汉等）的poi数据时，如果poi代码输入的是数据量较大的050000或者是060000，则会出现两种情况：1）停住不动，就一直停在还剩多少多少个数据那儿。2）爬到中途会提示key池用尽，可是明明key池还有很多的剩余量。PS：本人在爬取时同时输入了3个账号的key。

**Comment by Civitasv** [comment]
这个估计是高德后台停止返回数据了，目前还没想到很好的解决方法

**Comment by sobrietyyyyy** [comment]
> 这个估计是高德后台停止返回数据了，目前还没想到很好的解决

**Comment by sobrietyyyyy** [comment]
> > 这个估计是高德后台停止返回数据了，目前还没想到很好的解决

嗯嗯，题主加油！我的网速10m/s,左右，我发现线程输入6比60爬取速度快多了。
