### ISSUE TITLE
errorCode : 90003

### ISSUE THREAD

**Issue by AirisAir** [Civitasv/AMapPoi#7]
请问一下出现了errorCode : 90003;显示信息errorMessage : 任务终止 --- com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 2959 path $.pois[8].name
怎么办呢

**Comment by Civitasv** [comment]
这是一个json解析bug，不常出现，我这两天有时间修改一下

**Comment by Civitasv** [comment]
Fixed at 48f55f0505c4323ed76f3f6d75ab4acc038cd39d
