### ISSUE TITLE
GeoJSON范围爬取失败

### ISSUE THREAD

**Issue by CHD996** [Civitasv/AMapPoi#8]
![image](https://user-images.githubusercontent.com/52374567/168583544-6609959d-81a7-4b78-acde-f97215c48d12.png)
![image](https://user-images.githubusercontent.com/52374567/168583803-4db2e76a-7d3c-4e05-85a9-6663c98982bc.png)
按GeoJSON范围爬取失败，表现为读取文件后卡住不动，上面是使用到的参数，在老版本进行测试是能够顺利运行的

**Comment by Civitasv** [comment]
See release https://github.com/Civitasv/AMapPoi/tree/v2.0.1
